[package]
name = "kzg-commitment"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-poly-commit = "0.5.0"
ark-serialize = "0.5.0"
ark-std = "0.5.0"
derivative = "2.2.0"
itertools = "0.13.0"
keccak-asm = "0.1.4"
