[package]
name = "verkle-tree"
version = "0.1.0"
edition = "2021"

[dependencies]
kzg-commitment.workspace = true
ark-bn254 = "0.5.0"
ark-ec = "0.5.0"
ark-ff = "0.5.0"
ark-poly = "0.5.0"
ark-poly-commit = "0.5.0"
ark-std = "0.5.0"
keccak-asm = "0.1.4"
